In [3]:
import pandas as pd
import numpy as np
data = [1, 3, 5, np.nan, 6]
s = pd.Series(data)
print(s)
s2 = pd.Series((data), index=['a', 'b', 'c', 'd','e'])
print(s2)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
dtype: float64
a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
dtype: float64


In [6]:
import pandas as pd
data = {'Name': ['Ram', 'Robert','Rahim'],
'Age': [25, 30, 35],
'City': ['Ayodya', 'Chennai', 'Delhi']}
df = pd.DataFrame(data)
print(df)
print(data.values(), type(data.values()))
print(df.index, type(df.index))

     Name  Age     City
0     Ram   25   Ayodya
1  Robert   30  Chennai
2   Rahim   35    Delhi
dict_values([['Ram', 'Robert', 'Rahim'], [25, 30, 35], ['Ayodya', 'Chennai', 'Delhi']]) <class 'dict_values'>
RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [7]:
import pandas as pd
data_x = pd.Series([0, 1, 2, 3, 4, 5])
data_y = pd.Series([0, 1, 4, 9, 16, 25])
df = pd.DataFrame({'x_value': data_x, 'square(x)': data_y})
print(df)

   x_value  square(x)
0        0          0
1        1          1
2        2          4
3        3          9
4        4         16
5        5         25


In [8]:
df

x_value  square(x)
0        0          0
1        1          1
2        2          4
3        3          9
4        4         16
5        5         25

In [10]:
import pandas as pd
dates = pd.date_range("20130101", periods=6)
df_2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(dates)
print(df_2.dtypes)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
A    float64
B    float64
C    float64
D    float64
dtype: object


In [17]:
import pandas as pd
population_dict = {'California': 38332521,
'Texas': 26448193,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
print(population_dict,type(population_dict))
print(population,type(population))
population['California']
population['California':'Illinois']


{'California': 38332521, 'Texas': 26448193, 'Florida': 19552860, 'Illinois': 12882135} <class 'dict'>
California    38332521
Texas         26448193
Florida       19552860
Illinois      12882135
dtype: int64 <class 'pandas.core.series.Series'>


California    38332521
Texas         26448193
Florida       19552860
Illinois      12882135
dtype: int64

In [18]:
import numpy as np
A = np.random.randn(5, 3)
print(A, type(A))
dfA = pd.DataFrame(A)
print(dfA,type(dfA))

[[-0.91971793 -1.28028172 -1.30496064]
 [ 0.92130928 -1.72836046  0.61526095]
 [-0.04787092  0.14429741  1.43190601]
 [ 0.4927688  -1.57062299  0.55305066]
 [-1.1001505   1.18636922  0.32319914]] <class 'numpy.ndarray'>
          0         1         2
0 -0.919718 -1.280282 -1.304961
1  0.921309 -1.728360  0.615261
2 -0.047871  0.144297  1.431906
3  0.492769 -1.570623  0.553051
4 -1.100150  1.186369  0.323199 <class 'pandas.core.frame.DataFrame'>


In [25]:
data = {'A': [1, 2, np.nan, 4],
'B': [5, np.nan, 7, 8],
'C': [9, 10, 11, np.nan]}
df = pd.DataFrame(data)
print(df)
# Drop rows with missing values
df.dropna(inplace=True) # Modify df directly
print(df)

     A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN
     A    B    C
0  1.0  5.0  9.0


In [26]:
df.fillna(0, inplace=True)
print(df)
# Fill missing values with the mean of the column
df["C"].fillna(df["C"].mean(), inplace=True)
print(df)

     A    B    C
0  1.0  5.0  9.0
     A    B    C
0  1.0  5.0  9.0


<ipython-input-26-3bb75305a7c4>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["C"].fillna(df["C"].mean(), inplace=True)
